### ISSUE TITLE
blank result from segplot

### ISSUE THREAD

**Issue by Fatihlrcfs** [adamewing/methylartist#14]
Hi ,
Firstly thank you for generating this package. I am working on Nanopolish results and my plots come up with blank (actually you can see just a dot when you zoom in )for segplot. I am using your example command and blank results are below. many thanks.
Best

![megalodon_annotations data_nanopolish excl_ambig segmeth mc10 mr1 segplot](https://user-images.githubusercontent.com/75265865/167666361-4c936013-f310-495f-9051-ab1130229a33.png)
![megalodon_annotations data_nanopolish excl_ambig segmeth mc10 mr1 violin segplot](https://user-images.githubusercontent.com/75265865/167666378-f6b22fa9-99a3-4a57-a172-bdaaeb1665dd.png)

**Comment by adamewing** [comment]
Hi and thanks. My initial suspicion about what's going on here is that you might be feeding segmeth a file with one row per gene, is that right? If so, you'll just get the average methylation level across each segment and since you're doing one segment per annotation you're just getting one point for each - if that makes sense. If you want to look at methylation gene by gene you might be better served with the locus function. Segmeth/segplot works best for situations where you have many segments with a shared annotation (examples: promoters, CpG islands, CTCF sites, etc), in which case they all need the same annotation in the 4th column of the .bed-like file input to segmeth.

**Comment by adamewing** [comment]
Glad to hear that!
