### ISSUE TITLE
About sorting the GTF file

### ISSUE THREAD

**Issue by foxchase** [adamewing/methylartist#27]
Hello,
Regarding Homo_sapiens.GRCh38.97.chr.sorted.gtf.gz, 
1. how do you sort the GTF file?
2. where did you download the gtf and fasta? because different sources have minor differences.
Thank you in advance

**Comment by adamewing** [comment]
Methylartist doesn't come with or require any specific .gtf or .fasta references. If you're asking about the references used for the examples, I believe that's the Ensembl build 97 .gtf, and the genome reference is from the GATK resource bundle. Sorting would be by chromosome followed by coordinate as required for indexing via `tabix -p gtf`.

**Comment by nmflack** [comment]
I'm also having issues getting gene annotation data to display, specifically with `methylartist locus`. I'm analyzing allele-specific methylation for a *de novo* felid genome assembly. I lifted the GTF coordinates from the housecat reference genome onto the assembly using [Liftoff](https://github.com/agshumate/Liftoff). Our assembly contiguity is high and felid genomes are extremely colinear, so I assume the quality of the coordinate lift is adequate. 

I've attached a snippet of the assembly GTF file (`Fcat_contig_liftoff.sorted.gtf.gz`, output of Liftoff) for one random gene. Does anything about it stick out as something methylartist would not parse? The call below generates the included plot for the 'gene' feature region from the GTF, but no annotation appears. I have tried other loci, larger regions with `methylartist region`, and lifting from the equivalent Ensembl GTF instead of NCBI without any luck.

Thank you,
Nicole

```
methylartist locus --ref no_ctg001250_curated.wrapped.fasta \
--motif CG --phased --color_by_hp --ignore_ps --phase_labels 1:HP1,2:HP2 \
--nticks 6 --samplepalette husl --labelgenes --gtf Fcat_contig_liftoff.sorted.gtf.gz  \
-b longphase_haplotagged_pepper_mod.bam -i ctg000350:129382426-129462802
```

![longphase_haplotagged_pepper_mod ctg000350_129382426_129462802 m phased ms1 smw34 locus meth](https://user-images.githubusercontent.com/109246157/191365965-a8e2f7c3-7a89-4119-88a4-634cfbae3188.png)

[SMAD1_Fcat_contig_liftoff.sorted.gtf.txt](https://github.com/adamewing/methylartist/files/9611342/SMAD1_Fcat_contig_liftoff.sorted.gtf.txt)

**Comment by adamewing** [comment]
It's because the gtf records don't have a "gene_name" attribute. There's no good reason for me to not just use the "gene_id" attribute if gene_name is missing. I've fixed this in 920319 if you'd like to give it a try.

**Comment by nmflack** [comment]
This worked, thank you!

**Comment by foxchase** [comment]
The update is effective with pip or git install?
Thank you.
