### ISSUE TITLE
Use of Guppy after version 1.2.6

### ISSUE THREAD

**Issue by mari-ga** [adamewing/methylartist#38]
Hi!
First of all thanks for this wonderful tool.
I had a question regarding the use of methylartist with Guppy data after 1.2.6 version. I get that (db-guppy) is depreciated. Then how could we create a DB for Guppy? since there's no tsv files from Guppy for db-custom, or is it possible to use bed. files obtained from modbam2bed?

Thank you very much in advance for any help you can provide.

**Comment by adamewing** [comment]
Hi, glad it's useful to you!

Yes, this was done because newer versions of guppy, I think starting with guppy 6, can generate .bam files with modification tags (MM and ML tags) when using a model that calls modified bases. Using mod bams is much more efficient in both storage space required and in terms of the time it takes to generate the methylartist-specific sqlite db. Many other tools support .bam files with the modified base tags so if you haven't switched to using these I'd suggest giving it a try.

If you really do need to use the `db-guppy` function and it was working for you previously, you can add `--force` to the command-line and it will work as before.

**Comment by mari-ga** [comment]
Thank you very much for your quick answer.
Only one more question in the case of db-custom, specifically with deepSignal, only tsv files are given as output, therefore we don't have any bam files available.
I created a txt including the path for the .db but I get an error since no bam file was specified. could you please guide me with the use of the tool in a such as this, where no bam file is available?

`/methylartist locus -d /data/results/methylartist/deepsignal/barcode01/deepsignal_01.txt -i 1:3454:11382`

Thank you very much in advance!

**Comment by adamewing** [comment]
It looks like one of the preliminary steps in running deepsignal is basecalling the fast5s, which will generate fastqs. If you make a .bam file from the fastqs (e.g. via minimap2) then you should be good to go.

**Comment by mari-ga** [comment]
Working perfectly fine. Thank you very much for the help 😊
