### ISSUE TITLE
How to import multi-files？

### ISSUE THREAD

**Issue by BaylorLyu** [adamewing/methylartist#8]
I am little confuse about file import. If i have multi-samples, shuoud i merge to one file for import?

**Comment by adamewing** [comment]
Are you asking about making a methylartist `.db` file e.g. via `db-megalodon`? If so, then create one `.db` file per sample. Note that if you have a `.bam` file with modification info e.g. the `mod_mappings.bam` file generated by megalodon, you can skip this and use the `.bam` with modification information directly.

**Comment by BaylorLyu** [comment]
thanks for you reply.
I mean i have via db-megalodon but two groups, how to create .db for  methylartist. I want to campare two group.

**Comment by adamewing** [comment]
Hi, sorry for the delay. If you have a .bam file and a .db file (generated by methylartist) you can put them in a text file as follows:
```
sample1.bam sample1.db
sample2.bam sample2.db
sample3.bam sample3.db
```
(and so on for more samples)

Just those two fields are required but optionally, if you want to add a custom colour rather than using the sample color map, you can specify it in a third column.

Feed the text file to the `-d/--data` option on methylartist tools.

I think there's another example regarting this file, its expected contents, and its usage under "segmeth" in the github readme.
