### ISSUE TITLE
differentiated 5mC and 5hmC, or excluding one of the two

### ISSUE THREAD

**Issue by mvukk** [adamewing/methylartist#95]
Dear all,

I have aligned bam fila that have information for both 5mCG and 5hmCG. When I use this file to make plot for locus (code below) both marks are shown and for the same sample they are in the same color, thus it is hard to differentiate them. Is there a way to show only one mark (without remaking bam files) or to show them in different colors?

`
BAM1=aligned.bam
BAM2=aligned.bam
GENCODE=gencode.vM25.annotation.sorted.gtf.gz
ASSEMBLY=GRCm38.primary_assembly.mm10genome_release25.fa

time methylartist locus -i chr7:59,999,811-60,010,824 \
	-b $BAM1:#9a32a8,$BAM2:#32a852 \
	-g $GENCODE \
	-r $ASSEMBLY --labelgenes \
	-n CG -p 3,6,2,3,3 --width 30 --height 16
`

**Comment by adamewing** [comment]
Answered via email, putting here as well for reference:

The default is to show everything defined in the .bam file. You can choose which mods to show for "region" or "locus" using the -m/--mods option, so "-m h" is just 5hmC and "-m m" is just 5mC.

As for colouring, they're the same within .bam files because of the "-b $BAM1:#9a32a8,$BAM2:#32a852" - if you use a palette instead then the h and m mods will be different from one another but I haven't yet implemented a way to assign a specific colour to a specific mod within a .bam file. Should do that though.
